name: github pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Build Env
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build
        run: npm install -g yarn && yarn && yarn build

      - name: Deploy
        env:
          GITHUB_PAGES_TOKEN: ${{ secrets.GP_TOKEN }}
        run: yarn deploy
